export const DEFAULT_REFERRER_REWARD_POINTS = 1000;
export const DEFAULT_REFEREE_REWARD_POINTS = 10000;
export const DEFAULT_COMMISSION_RATE_PERCENT = 3;
export const DEFAULT_RFQ_REQUEST_POINT_COST = 5000;
